name: Publish to Site

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
  
    - name: Run tests
      run: cargo test

    - name: Build
      run: cargo build --release

    - name: Upload to S3
      run: aws s3 cp target/release/terraform-visualizer s3://${{ secrets.AWS_S3_BUCKET }}/executables/terraform-visualizer/terraform-visualizer
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}